#!/bin/bash
export LATEST_BRANCHES="develop master"
if [[ $LATEST_BRANCHES == *"$SOURCE_BRANCH"* ]];
    then
        export SOURCE_BRANCH=3.7.1
fi

docker build --build-arg VERSION=$SOURCE_BRANCH -t $IMAGE_NAME .
